apiVersion: v1
entries:
  vs:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-26T08:49:50.1204985Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 7427a985f1d52c849baa11324f3cec24ef6ad50a8bba6f4ad8d79c3bfd6ad1ef
    home: vs.zuid-drecht.nl
    icon: vs.zuid-drecht.nl
    name: vs
    urls:
    - vs-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-26T08:49:50.1155601Z"
